default:
  models:
    Employee: read
    EmployeeDepartment: read
    VendorInvoice: read
    Vendor: read
    Vendor: read
    LedgerEntryDetail: read
    LedgerEntryDetail: read
    LedgerEntry: read
    LedgerEntry: read
    LedgerAccount: read
    PostalAddress: read
    Company: read
    Team: read
    Contact: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Employee: manage
    EmployeeDepartment: manage
    VendorInvoice: manage
    Vendor: manage
    Vendor: manage
    LedgerEntryDetail: manage
    LedgerEntryDetail: manage
    LedgerEntry: manage
    LedgerEntry: manage
    LedgerAccount: manage
    PostalAddress: manage
    Company: manage
    Team: manage
    Contact: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage
